#!/bin/bash
export ARCH=arm64
export SUBARCH=arm64
export CLANG_PATH="${HOME}/joseasensio/platform_prebuilts_clang_host_linux-x86/7.0"
export CROSS_COMPILE="${HOME}/joseasensio/gcc-prebuilts/bin/aarch64-linux-gnu-"
export CC="$CLANG_PATH/bin/clang"
export CLANG_TRIPLE="aarch64-linux-gnu-"
export KBUILD_COMPILER_STRING="`cat $CLANG_PATH/VERSION`"
z2_plus(){
zipname="OverPoweredKernel(z2_plus_Non-treble).zip"
export KBUILD_BUILD_USER="z2_plus"
export KBUILD_BUILD_HOST="Characteress"
make O=out mrproper&&make O=out z2_plus_defconfig&&make O=out -j16

cp -f out/arch/arm64/boot/Image.gz-dtb ~/AnyKernel2
cd ~/AnyKernel2
git checkout z2_plus_non-treble
zip -r "$zipname" *
cp -f "$zipname" ~
rm -f "$zipname"

}

if [ "$1" == z2_plus ]
then
z2_plus
fi
